MODEL_CONFIG="llm.eval_gaudi"
COMMIT_HASH=HEAD
AGENT=CodeActAgent
EVAL_LIMIT=10
MAX_ITER=6
NUM_WORKERS=2
DATASET="princeton-nlp/SWE-bench_Lite"
SPLIT="test"
N_RUNS=1
MODE="swe"
POISSON_RATE=2.0

./evaluation/benchmarks/swe_bench/scripts/run_infer.sh $MODEL_CONFIG $COMMIT_HASH $AGENT $EVAL_LIMIT $MAX_ITER $NUM_WORKERS $DATASET $SPLIT $N_RUNS $MODE $POISSON_RATE